services:
  - type: web
    name: fantasy-cricket-champ
    env: node
    nodeVersion: 16.19.1
    buildCommand: node fix-build.js
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
