services:
  - type: web
    name: fantasy-cricket-champ
    env: node
    buildCommand: |
      chmod +x render-build.js
      node render-build.js
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
