services:
  - type: web
    name: fantasy-cricket-champ
    env: node
    buildCommand: node render-setup.cjs
    startCommand: NODE_ENV=production node server-wrapper.js
    envVars:
      - key: NODE_ENV
        value: production
