services:
  - type: web
    name: fantasy-cricket-champ
    env: node
    nodeVersion: 16.x # Use an older Node.js version for more stable CJS behavior
    buildCommand: node render-build-script.cjs
    startCommand: node server-wrapper.cjs
    envVars:
      - key: NODE_ENV
        value: production
