services:
  - type: web
    name: fantasy-cricket-champ
    env: node
    buildCommand: node build-fix.cjs
    startCommand: NODE_ENV=production node --experimental-modules run.mjs
    envVars:
      - key: NODE_ENV
        value: production
