services:
  - type: web
    name: fantasy-cricket-champ
    env: node
    nodeVersion: 18.x
    buildCommand: |
      # Copy our special package.json over the original one
      cp render-package.json package.json
      # Run the build script from our special package.json
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
