services:
  - type: web
    name: fantasy-cricket-champ
    env: node
    buildCommand: |
      # Make custom build script executable
      chmod +x render-build.js
      
      # Set environment variables to ensure we use our custom config
      export VITE_CONFIG_PATH=vite.render.config.js
      export NODE_OPTIONS="--experimental-modules --es-module-specifier-resolution=node"
      
      # Run the custom build script
      node render-build.js
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
