services:
  - type: web
    name: fantasy-cricket-champ
    env: node
    nodeVersion: 16.x
    buildCommand: node direct-build.js
    startCommand: NODE_ENV=production node start-server.cjs
    envVars:
      - key: NODE_ENV
        value: production
